Repository Project60/org.project60.banking, pull requests merged in 2022-09, with the labels that each got.

#351 Update Import.tpl
  extension/templates/CRM/Banking/Page/Import.tpl
Labels: status:reviewed and tested

#352 Update banking.po
  extension/l10n/de_DE/LC_MESSAGES/banking.po
Labels: status:needs work

#347 fix #346 | wrong parameter name for option group id
  extension/CRM/Banking/BAO/PluginInstance.php
Labels: bug, status:reviewed and tested

#280 #279 matching of existing contribution on the same date.
  extension/CRM/Banking/PluginImpl/Matcher/ExistingContribution.php
Labels: enhancement, status:needs work

#349 Change statements filter method from GET to POST
  extension/templates/CRM/Banking/Page/Statements.tpl
Labels: enhancement, status:needs review
