Repository Project60/org.project60.banking, pull requests merged in 2025-01, with the labels that each got.

#435 Fix NavMenu Icon for Compatibility with CiviCRM Core 5.77/Font Awesome 6
  banking.php
Labels: enhancement

#407 fix storing of json_editor_mode
  CRM/Admin/Form/Setting/BankingSettings.php
Labels: bug

#413 fix #409: add option to preserve original receive_date
  CRM/Banking/PluginImpl/Matcher/DefaultOptions.php
  CRM/Banking/PluginImpl/Matcher/ExistingContribution.php
Labels: enhancement, feature, status:needs review

#398 Fix for #397
  CRM/Banking/Matcher/Context.php
Labels: enhancement

#446 Add CSV parse options enclosure and escape - #445
  CRM/Banking/PluginImpl/Importer/CSV.php
Labels: feature

#399 Remove some 'not defined' notices in importer code
  CRM/Banking/PluginImpl/Importer/XML.php
Labels: enhancement
